baseURL = "https://ntcir.datasearch.jp/"
languageCode = "en-us"
title = "NTCIR-15 Data Search"
theme = "hugo-theme-bootstrap4-blog"

[markup.goldmark.renderer]
  unsafe= true

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

#[[menu.sidebar]]
#  name = "link 1"
#  url = "https://example.com"
#
#[[menu.sidebar]]
#  name = "Link 2"
#  url = "https://example.org"

[[menu.navbar]]
  name = "Task"
  url = "#task"
  weight = 1

[[menu.navbar]]
  name = "Data & Tool"
  url = "#data"
  weight = 2

[[menu.navbar]]
  name = "Submission"
  url = "#submission"
  weight = 3

[[menu.navbar]]
  name = "Evaluation"
  url = "#evaluation"
  weight = 4

[[menu.navbar]]
  name = "Organizers"
  url = "#organizers"
  weight = 5

[params]
  author = "NTCIR-15 Data Search Organizers"

  # Description/subtitle for homepage (can be Markdown)
  description = "A shared task on ad-hoc retrieval for governmental statistical data"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # Eyecatch images
  images = ["/logo.png"]

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = false

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    # twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
